baseURL = "https://boorbit.com/"
languageCode = "zh-cn"
title = "BoOrbit"
theme = "blowfish"

defaultContentLanguage = "zh-cn"
enableRobotsTXT = true
enableEmoji = true
hasCJKLanguage = true
summaryLength = 30
buildDrafts = false
buildFuture = false

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  colorScheme = "avocado"
  defaultAppearance = "dark"
  autoSwitchAppearance = false
  enableSearch = true
  enableCodeCopy = true
  mainSections = ["posts"]

  [params.author]
    name = "BoOrbit"
    headline = "AI · HomeLab · Cloud · Life  "
    bio = "记录我的家庭实验室、开源应用、AI工具、技术学习与生活观察。"

    image = "img/Bo.png"
    links = [
      { github = "https://github.com/bearbobo" },
    ]

  [params.homepage]
    layout = "profile"
    showRecent = true
    showRecentItems = 6
    showMoreLink = true
    showMoreLinkDest = "posts"
    cardView = true
    cardViewScreenWidth = false
    layoutBackgroundBlur = true
    homepageImage = "img/background.png"

  [params.article]
    showDate = true
    showAuthor = true
    showHero = true
    heroStyle = "background"
    showBreadcrumbs = true
    showReadingTime = true
    showTableOfContents = true
    showTaxonomies = true
    sharingLinks = ["telegram", "whatsapp", "email"]

  [params.list]
    showHero = false
    showBreadcrumbs = true
    showSummary = true
    cardView = true
    groupByYear = true

  [params.footer]
    showMenu = true
    showCopyright = true
    showThemeAttribution = false
    showScrollToTop = true

[menu]
  [[menu.main]]
    name = "首页"
    pageRef = "/"
    weight = 10

  [[menu.main]]
    name = "文章"
    pageRef = "posts"
    weight = 20

  [[menu.main]]
    name = "分类"
    pageRef = "categories"
    weight = 30

  [[menu.main]]
    name = "关于"
    pageRef = "about"
    weight = 40

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
